all:
	@nim make
clean:
	@nim clean

GIT_REPO = c:/.ccache/life_test/life_wNim
rel:
	cp life_win.nim    $(GIT_REPO)/
	cp config.nims     $(GIT_REPO)/
	cp setenv.bat      $(GIT_REPO)/
	cp Makefile        $(GIT_REPO)/
	cp *.life          $(GIT_REPO)/
	cp *.dll           $(GIT_REPO)/
